version: v0-winbuild-{build}

build: off

clone_folder: c:\gopath\src\github.com\cosmo0920\fluent-bit-go-loki

environment:
  matrix:
    - GOPATH: c:\gopath
      PATH: C:\msys64\mingw64\bin\;%PATH%
      PLATFORM: x64
      GOARCH: amd64
      GOROOT: c:\go
    - GOPATH: c:\gopath
      PATH: C:\msys64\mingw32\bin\;%PATH%
      PLATFORM: win32
      GOROOT: c:\go-x86
      GOARCH: 386

stack: go 1.11

before_test:
  - choco install make
  - set GOARCH=%GOARCH%
  - set PATH=%GOROOT%\bin;C:\%GOPATH%\bin;%PATH%
  - go vet ./...

test_script:
  - make
  - 7z a fluent-bit-go-loki-%PLATFORM%.zip out_loki.dll
  - set ARTIFACT=fluent-bit-go-loki-%PLATFORM%.zip

on_success:
  - ps: Push-AppveyorArtifact $Env:ARTIFACT

artifacts:
  - path: fluent-bit-go-loki-*.zip
    name: binary

deploy:
  provider: GitHub
  auth_token:
    secure: 7XdoaFISgIXPlmVTNkMMS5cOhQzCQ06N1ksjNsres/dAyMYbT8CTxnV9KgHabwww
  artifact: binary          # upload zip archive to release assets
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
